# Why Numpy

## 1) Memory Usage

In [4]:
import numpy as np
import time 
import sys 

array = np.arange(100)
print("The size of the Numpy array here is:", array.size*array.itemsize)

The size of the Numpy array here is: 400


In [2]:
list_ = range(0,100)
print("The size of the list here is:",sys.getsizeof(1)*len(list_))

The size of the list here is: 2800


## 2) Faster!! 

In [5]:
size = 100000

#Create 2 lists of size 1lakh
list1 = range(size)
list2 = range(size)

#Create 2 arrays of the same size 
arr1 = np.arange(size)
arr2 = np.arange(size)

In [9]:
start = time.time()
for x,y in zip(list1,list2):
    res = x+y
print("The total time taken for execution is:",(time.time()-start)*1000)

The total time taken for execution is: 54.37493324279785


In [10]:
start = time.time()
res = arr1+arr2
print("The total time taken for execution is:",(time.time()-start)*1000)

The total time taken for execution is: 0.9977817535400391


1596255679.9692137

## Convienient 

In [13]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print("The addition: ",a1+a2)
print("The subtraction: ",a1-a2)
print("The multiplication: ",a1*a2)

The addition:  [5 7 9]
The subtraction:  [-3 -3 -3]
The multiplication:  [ 4 10 18]


In [ ]:
'''
Install 
!pip install numpy 
!conda install numpy --y
!pip3 install numpy
'''

In [2]:
# Import numpy 
import numpy as np

In [3]:
from numpy import array

In [4]:
a1 = np.array([1,2,28])

In [5]:
a1

array([ 1,  2, 28])

In [20]:
type(a1)

numpy.ndarray

'''
N-D - Stands for 'N'-Dimentional Array
'''
1-D Matrix - Rows
2-D Matrix - Rows,columns
3-D Matrix (Tensors) - Rows,columns and depth

In [28]:
lst = [1,2,"batch14"]
type(lst[1])

int

In [29]:
lst = [1,2,"batch14"]
type(lst[2])

str

In [26]:
arr = np.array([1,2,3,"Batch14"])
print(type(arr[0]))

<class 'numpy.str_'>


In [30]:
arr = np.array([1,2,3,"Batch14"])
print(type(arr[2]))

<class 'numpy.str_'>


In [31]:
print(np.__version__)

1.15.1


In [35]:
arr.shape

(4,)

In [36]:
arr_2d = np.array([[1,2,3],[5,6,7]])

In [39]:
arr_2d

array([[1, 2, 3],
       [5, 6, 7]])

In [40]:
arr_2d[1][1]

6

In [41]:
arr_2d.shape

(2, 3)

In [42]:
arr_2d[1:,:2]

array([[5, 6]])

1) Create a 2d Array with shape 3X3 with numpy

2) Create a 3d Array of shape 1X4X3 with numpy

In [47]:
array_3d = np.array([[[1,5,7],[4,5,6],[7,8,9],[8,9,10]],[[1,15,17],[14,15,16],[17,18,19],[8,9,10]]])

In [48]:
array_3d

array([[[ 1,  5,  7],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 8,  9, 10]],

       [[ 1, 15, 17],
        [14, 15, 16],
        [17, 18, 19],
        [ 8,  9, 10]]])

In [49]:
array_3d.shape

(2, 4, 3)

In [20]:
array_3d = np.array([[[1,5,7],[4,5,6],[7,8,9],[8,9,10]],[[1,5,7],[4,5,6],[7,8,9],[8,9,10]]])

In [118]:
array_3d

array([[[ 1,  5,  7],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 8,  9, 10]],

       [[ 1,  5,  7],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 8,  9, 10]]])

In [119]:
array_3d.shape

(2, 4, 3)

## Functions involved in creating an array

In [67]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
a = a.reshape((1,4,4))

In [68]:
#Reshape: translates or converts the shape of the array 
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [76]:
#linspace: This function generates elements which are equally spaced from each other!
np.linspace(0.50,50.45,10) #---> Start, Stop and Number of elements(Equally spaced)

array([ 0.5 ,  6.05, 11.6 , 17.15, 22.7 , 28.25, 33.8 , 39.35, 44.9 ,
       50.45])

In [87]:
#arange: Generated values based on the 'Step' you specify between start and stop
np.arange(90,10,-10) # --> Start, Stop and Step 

array([90, 80, 70, 60, 50, 40, 30, 20])

In [79]:
lst = list(range(0,100))

In [84]:
lst[0:90:10]

[0, 10, 20, 30, 40, 50, 60, 70, 80]

## Create an array with values from 68 - 24 (just the even numbers)

In [91]:
#Zeros - Fills the specified shape with zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [92]:
#Ones - fills the specified shape with ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.pad()

In [93]:
[[1,1,1],
 [1,1,1,],
 [1,1,1,]]

[[1, 1, 1], [1, 1, 1], [1, 1, 1]]

In [ ]:
[[0,0,0,0,0],
 [0,1,1,1,0],
 [0,1,1,1,0],
 [0,1,1,1,0],
 [0,0,0,0,0]]

In [6]:
a = np.zeros((5,5))
a[1:4,1:4] =1

In [7]:
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
a = np.ones((3,3))
x = np.pad(a,pad_width=1, mode = 'constant',constant_values =4)

In [18]:
x

array([[4., 4., 4., 4., 4.],
       [4., 1., 1., 1., 4.],
       [4., 1., 1., 1., 4.],
       [4., 1., 1., 1., 4.],
       [4., 4., 4., 4., 4.]])

In [100]:
#identity matrix - with just the diagonal elements as one
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [101]:
#Diagonal Matix
np.diag([1,2,5,6,7])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 7]])

In [ ]:
#operations with numpy array

In [102]:
#copy 
arr = np.array([24,12,11])
dup = arr.copy()
arr[0] = 55

print(arr)
print(dup)

[55 12 11]
[24 12 11]


In [103]:
#View 
arr = np.array([24,12,11])
x = arr.view()
arr[0] = 55

print(arr)
print(x)

[55 12 11]
[55 12 11]


In [104]:
##Itration through an array 

In [129]:
arr.shape 

(3,)

In [106]:
for i in arr: 
    print(i)

55
12
11


In [112]:
arr_2d

array([[1, 2, 3],
       [5, 6, 7]])

In [130]:
for row in arr_2d:
    print(row)
    for ele in row:
        print(ele)

[1 2 3]
1
2
3
[5 6 7]
5
6
7


In [123]:
arr_2d.shape

(2, 3)

In [124]:
array_3d.shape

(2, 4, 3)

In [128]:
array_3d.shape

(2, 4, 3)

In [21]:
for i in array_3d:
    for j in i:
        for k in j:
            print(k)

1
5
7
4
5
6
7
8
9
8
9
10
1
5
7
4
5
6
7
8
9
8
9
10


## Addition

In [132]:
arr1 = np.array(range(1,17,1))
arr1 = arr1.reshape(4,4)

In [133]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [134]:
arr2 = np.array(range(10,170,10))
arr2 = arr2.reshape(4,4)

In [135]:
arr2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [136]:
arr1+arr2

array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 110, 121, 132],
       [143, 154, 165, 176]])

In [137]:
a = np.array([1,3,4,5])
b = np.array([1,2])

In [138]:
a+b

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [ ]:
sum_arr = np.add(arr1,arr2)

In [139]:
print(np.add(arr1,arr2))

[[ 11  22  33  44]
 [ 55  66  77  88]
 [ 99 110 121 132]
 [143 154 165 176]]


In [140]:
#Subtraction

In [141]:
arr1-arr2

array([[  -9,  -18,  -27,  -36],
       [ -45,  -54,  -63,  -72],
       [ -81,  -90,  -99, -108],
       [-117, -126, -135, -144]])

In [142]:
print(np.subtract(arr1,arr2))

[[  -9  -18  -27  -36]
 [ -45  -54  -63  -72]
 [ -81  -90  -99 -108]
 [-117 -126 -135 -144]]


In [143]:
#Multiply

In [144]:
arr1*arr2

array([[  10,   40,   90,  160],
       [ 250,  360,  490,  640],
       [ 810, 1000, 1210, 1440],
       [1690, 1960, 2250, 2560]])

In [148]:
np.multiply(arr1,arr2)

array([[  10,   40,   90,  160],
       [ 250,  360,  490,  640],
       [ 810, 1000, 1210, 1440],
       [1690, 1960, 2250, 2560]])

## Matrix Multiplication

In [146]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [147]:
arr2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [145]:
np.dot(arr1,arr2)

array([[ 900, 1000, 1100, 1200],
       [2020, 2280, 2540, 2800],
       [3140, 3560, 3980, 4400],
       [4260, 4840, 5420, 6000]])

## Divide 

In [149]:
np.divide(arr1,arr2)

array([[0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1]])

In [150]:
arr1*100

array([[ 100,  200,  300,  400],
       [ 500,  600,  700,  800],
       [ 900, 1000, 1100, 1200],
       [1300, 1400, 1500, 1600]])

## Joining  two numpy arrays

In [23]:
arr1 = np.array([1,2,3,5])
arr2 = np.array([5,6,7,8])
np.stack((arr1,arr2))

array([[1, 2, 3, 5],
       [5, 6, 7, 8]])

In [155]:
np.stack((arr1,arr2),axis = 1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [5, 8]])

In [27]:
np.stack((arr1,arr2),axis = 1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [5, 8]])

In [157]:
np.hstack((arr1,arr2))

array([1, 2, 3, 5, 5, 6, 7, 8])

In [158]:
#Vstack - Stacks into same column 
np.vstack((arr1,arr2))

array([[1, 2, 3, 5],
       [5, 6, 7, 8]])

In [159]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 5, 5, 6, 7, 8])

In [160]:
## Splitting

In [161]:
arr = np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 5, 5, 6, 7, 8])

In [162]:
np.array_split(arr,4)

[array([1, 2]), array([3, 5]), array([5, 6]), array([7, 8])]

In [164]:
np.sort(arr)

array([1, 2, 3, 5, 5, 6, 7, 8])

In [167]:
arr = np.array([1,2,3,4,5,6,7])
ele= np.array_split(arr,4)

In [170]:
type(ele)

list